---

- name: apache2 disable all website
  shell: rm -rf /etc/apache2/sites-enabled/*

- name: a2enmod ssl
  command: a2enmod ssl

- name: a2ensite default
  command: a2ensite 000-default
  notify:
    - restart apache