---
# Path: system/timezone/tasks

- name: set timezone variables
  copy: content={{ system_timezone }}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update timezone