---
# Path: php/php5-fpm/tasks

- name: install php5-fpm and its modules
  apt: name={{item}} force=yes state=installed
  with_items:
    - php5-fpm
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-redis
  tags:
    - php5-fpm

# Edit php5-fpm default configuration
- replace: dest=/etc/php5/fpm/php.ini regexp='short_open_tag = Off' replace='short_open_tag = On'
- replace: dest=/etc/php5/fpm/php.ini regexp='max_execution_time = 30' replace='max_execution_time = 300'
- replace: dest=/etc/php5/fpm/php.ini regexp='max_input_vars = 1000' replace='max_input_vars = 10000'
- replace: dest=/etc/php5/fpm/php.ini regexp=';date.timezone =' replace='date.timezone = Europe/Rome'
- replace: dest=/etc/php5/cli/php.ini regexp=';date.timezone =' replace='date.timezone = Europe/Rome'
- replace: dest=/etc/php5/fpm/php.ini regexp='memory_limit = 128M' replace='memory_limit = 256M'

# Edit php5-fpm pool default configuration
- replace: dest=/etc/php5/fpm/pool.d/www.conf regexp='listen = /var/run/php5-fpm.sock' replace='listen = 127.0.0.1:9000'
  notify: restart php5-fpm