---

- stat: path=/usr/local/bin/composer
  register: composer
  tags:
    - composer

- name: install composer
  shell: "{{ item }}"
  with_items:
    - wget https://getcomposer.org/composer.phar
    - chmod +x ./composer.phar
    - mv ./composer.phar /usr/local/bin/composer
    - /usr/local/bin/composer self-update
  when: composer.stat.exists == false
  tags:
    - composer

- name: update composer
  shell: "{{ item }}"
  with_items:
    - composer selfupdate
  when: composer.stat.exists == true
  tags:
    - composer